Modified to add child tag
nttcom/threatconnectome pull request #117
Opened 2024-03-13 01:24 UTC by TsurutaYoshiki

## PR の目的
- pteamの画面でアクションを作成する際に、Topictagが親の場合その子供のタグが選択できないバグを修正しました。

## 経緯・意図・意思決定
- Topictagに親タグのみ選択されていても、アクション作成時に親と子供のタグ両方を登録できるようにしました。
- 条件分岐でvalidTagNamesに子供のタグを追加できるようにしました。

2024-03-13 05:25 UTC, mshim03 requested changes
tag という変数名が重複している、ループの中でやる必要がなさそうな処理をループの中でやっている、というので処理が複雑になっているように見えます。修正お願いします

2024-03-13 05:25 UTC, mshim03 commented on web/src/components/PTeamEditAction.jsx
> +          validTagNames.add(tag[0].tag_name);
先頭要素しか使わないならfindで良さそうです
https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Array/find

2024-03-13 05:25 UTC, mshim03 commented on web/src/components/PTeamEditAction.jsx
> +          const tag = allTags.filter((tag) => tag.tag_id === presetTagId);
allTags をフィルターしたリストに対してforEachで関数作っているのですが、引数のtagと同名の tag という変数を定義して処理しているため処理がよくわかりません。

この処理ってループの中でやる意味ありますか？allTags の中から presetTagId と合致しないものを抽出しているわけで、ループの中でやる必要がなさそうに見えますが。
```
        if (tag.tag_id !== presetTagId && tag.tag_id === presetParentTagId) {
          const tag = allTags.filter((tag) => tag.tag_id === presetTagId);
```

2024-03-13 06:02 UTC, TsurutaYoshiki commented on web/src/components/PTeamEditAction.jsx
> +          const tag = allTags.filter((tag) => tag.tag_id === presetTagId);
127行目の部分については、validTagNamesに子タグの名前を入れるためにallTagsとpresetTagIdを使って子供タグの名前を取ってきている部分です。おっしゃる通り、ループの外で行うように修正します。
const tagについては名前が重複しているので修正します。

2024-03-13 06:19 UTC, TsurutaYoshiki commented
@mshim03 
ループ外に処理を実装しました。
また変数名が重複していた部分に関しては、tag→presetTagに変更しました。

2024-03-13 06:50 UTC, mshim03 reviewed
alltags のforEach でやる意味が見えなかったので確認お願いします

2024-03-13 06:50 UTC, mshim03 commented on web/src/components/PTeamEditAction.jsx
> +        }
ここで tag_id === presetParentTagId の判定を通した上で `validTagNames.add(presetTag.tag_name);` する意味ってあります？

117行目で以下のようにするのと何か違いますかね？
```
const presetTag = allTags.find((tag) => tag.tag_id === presetTagId);
validTagNames.add(presetTag.tag_name);
```

alltags には現状システム上全てのtagが入っているという認識なので、 `if (tag.tag_id !== presetTagId && tag.tag_id === presetParentTagId)` は必ず一つtrue になるものがあるのでは
(ループ内でやる意味はないのでは？)

2024-03-14 01:18 UTC, TsurutaYoshiki commented
@mshim03 
forEachの外に処理を記述し117行目に以下のコードを追加しました。
```
const presetTag = allTags.find((tag) => tag.tag_id === presetTagId);
validTagNames.add(presetTag.tag_name);
```
またEdit Topicでも同様にactionの設定ができるように、TopicModal.jsxにも同じ処理を付け加えました。

2024-03-14 01:30 UTC, mshim03 approved these changes
LGTM

2024-03-14 01:30 UTC, merged