Refactor/consolidation of db processing2
nttcom/threatconnectome pull request #125
Opened 2024-03-27 06:29 UTC by soum-kazuaki

## PR の目的

- SQL 操作（特に永続化）の集約

## 経緯・意図・意思決定

- 永続化処理は基本的に app/persistence.py に実装する
- パフォーマンスなどの理由でやむを得ず特殊な実装を行う場合は app/command.py に実装する
  - 本 PR では時間的な都合で整理しきれていない処理も app/command.py に含まれている
- HTTPException は原則的に app/routers/*.py からのみ raise する

本 PR では処理レイヤの分離が種目的であり、処理内容の調整には不十分な箇所もある

2024-03-27 09:58 UTC, mshim03 requested changes
以下の対応は必須でお願いします

- persistenceにはロジックを持たせず、単純なReac / Create / Delete で構成するように変更をお願いします
  - persistence.expire_petam_invitations, persistence.expire_ateam_invitations は変更お願いします
-  get_topic_ids_by_pteam_id_and_tag_id は名前とやっていることが違いそうです

2024-03-27 09:58 UTC, mshim03 commented on api/app/routers/pteams.py
> +    persistence.expire_pteam_invitations(db)
persistence にはロジックを持たない、単純な Read/ Create / Delete なメソッドにとどめてください
このケースは invitation を取得 -> python側でexpire の判定を行うようにしてください

2024-03-27 09:58 UTC, mshim03 commented on api/app/routers/pteams.py
> +    topic_ids = command.get_topic_ids_by_pteam_id_and_tag_id(db, pteam_id, tag_id, True)
関数の名前とやっていることにズレがありそうです (この関数名だと topic_ids と tag_id から関係あるtopic_ids を取得するだけに見えます)

2024-03-27 09:58 UTC, mshim03 commented on api/app/command.py
> +def get_topic_ids_by_pteam_id_and_tag_id(
関数名とやっていることにズレがありそうです (statsuなどが関係してますし、order byもしているので単純に関係あるtopicを取るだけではないはず)

2024-03-28 06:45 UTC, soum-kazuaki commented on api/app/persistence.py
> +    )
ミーティングでPO交えて相談したとおり、 `actionlogs.search_log()` の（当面）廃止に伴い上記は関数ごと削除しました。

2024-03-29 10:08 UTC, mshim03 approved these changes
LGTM

2024-03-29 10:15 UTC, merged