Improved test alert coverage
nttcom/threatconnectome pull request #147
Opened 2024-04-16 10:35 UTC by TsurutaYoshiki

## PR の目的
- test_alert.pyにあるテストの名前を変更しました。
- パラメトリックを用いてテストを整理しました。
- テストケースを追加しました。

## 経緯・意図・意思決定
### 名前変更について
- test_pick_alert_target_for_new_topic__tags → test_pick_alert_when_the_matching_tag_exists_when_the_topic_is_create
- test_pick_alert_target_for_new_topic__threshold → test_pick_alert_when_the_threat_impact_of_a_topic_is_less_than_the_alert_threat_impact_of_a_pteam
- test_pick_alert_target_for_new_topic__auto_closed → test_pick_alert_when_the_tag_is_not_auto_closed_and_remains_in_the_tag

###パラメトリックを用いてテストを整理について
- test_pick_alert_when_the_threat_impact_of_a_topic_is_less_than_the_alert_threat_impact_of_a_pteamとtest_pick_alert_when_the_tag_is_not_auto_closed_and_remains_in_the_tagの2つのテストについてパラメトリックを用いたテストに変更しました。

###テストケースを追加について
- test_pick_alert_when_the_matching_tag_exists_when_the_topic_is_createdについてテストを2つテストを追加しました
- 単一トピックに複数親のタグで合致するケースと単一トピックに複数子のタグで合致するケースを追加しました。

2024-04-17 01:14 UTC, TsurutaYoshiki commented
## test_pick_alert_when_the_matching_tag_exists_when_the_topic_is_createdについて相談
test_pick_alert_when_the_matching_tag_exists_when_the_topic_is_createdについては、構造が複雑で変化してパラメータがいくつかあったため、パラメタライズ用いたテストに変えることが難しく、そのままにしています。このテストについては元のままでもよろしいでしょうか？

## test_pick_alert_target_for_new_topic__auto_closed について相談
このテストをtest_pick_alert_when_the_tag_is_not_auto_closed_and_remains_in_the_tag
test_pick_alert_when_the_tag_with_and_without_auto_closed_and_remains_in_the_tagの2つに分割したのですが、元のテストの形にした方が良いでしょうか？
2つに分けた理由としましては、扱っているパラメータの数が違っており、1つの関数で実装しようとするとパラメータが1つの時と、2つの時で条件分岐を作りテストを行う実装になると思いました。条件分岐を作ってテストを行うと可読性が下がると思い分けました。分けたら分けたでと同じ処理が重複しているので、結局は元のテストの方が見た目としてはいいように感じたのですが、今の形か元の形どちらが良いでしょうか？

2024-04-18 09:43 UTC, TsurutaYoshiki commented
@mmasaki 
テストの運用保守をしやすくするために、テストの構造を大きく変更しました。

### test_pick_alert_target_for_new_topic__tagsについて
- テスト準備で共通している部分を@pytest.fixtureでまとめました。
- 1つのテスト関数で確かめたいことはなるべく1つになるように、関数、クラスを分離しました。
そのためclass TestPTeamHasParentTagとclass TestPTeamHasChildTagについては重複している部分があります。
- テストで使用するパラメータをわかりやすくするため@pytest.mark.parametrizeを使用しました。
- class TestPTeamHasParentTag
    - pteamに親タグを登録
    - topicに親タグか子タグを登録した時にアラートされるかどうかを検証
- class TestPTeamHasChildTag
   - pteamに子タグを登録
   - topicに親タグか子タグを登録した時にアラートされるかどうかを検証

### test_pick_alert_when_the_tag_is_not_auto_closed_and_remains_in_the_tagとtest_pick_alert_when_the_tag_with_and_without_auto_closed_and_remains_in_the_tagについて
- こちらのテストも上記と同じような理由で構造を変更しました。
- 2つあったテストをclass TestTopicHasVersionに統合し、共通している部分を@pytest.fixtureでまとめました。

2024-04-18 10:58 UTC, mshim03 requested changes
以下は対応お願いします
- _gen_pteam_params を使用しない
- 不要なparameterize をなくす (関数的にtrue/false以外にはなり得ないところが多い)
- find_expectedの修正

2024-04-19 04:02 UTC, TsurutaYoshiki commented on api/app/tests/medium/test_alert.py
> +    )
@mshim03 
@pytest.mark.parametrizeを使用した意図は入力したデータと返ってきて欲しいデータが見やすくなると思い使いました。

Falseをparameterにしない場合、現在下記のようになっているのを
`assert xxxxxx == expected`

次のように直す認識であっています。
`assert xxxxxxx == False`

2024-04-19 04:13 UTC, mshim03 commented on api/app/tests/medium/test_alert.py
> +    )
@TsurutaYoshiki 
その認識であってます。このテストは `it should not alert` なので、アラートされないパターンをテストしていると言うことは関数名から読み取れます。
その情報があるのに False がついているのは読み手に余計な情報を与えているかなと思います

2024-04-19 04:32 UTC, TsurutaYoshiki commented
@mshim03
指摘事項を踏まえて以下の3つを変更しました。
- _gen_pteam_params関数を削除し、素直にパラメータを定義して create_pteam に渡すようにしました。
- 不要なparameterize を無くしました。
`test_it_should_not_alert`となっている関数のところで、expectedを削除しました。
- find_expectedの名前を`check_tag_in_alert_target`変更しました。

2024-04-19 05:03 UTC, mshim03 approved these changes
LGTM

2024-04-19 05:03 UTC, merged