add get_tag API
nttcom/threatconnectome pull request #159
Opened 2024-05-07 08:02 UTC by dejima-shikou

## PR の目的
 - GET /tags/{tag_id} エンドポイントを作成

## 経緯・意図・意思決定
 - tagidからタグ情報を取得できるようにする。

2024-05-07 09:30 UTC, mshim03 requested changes
テストについて修正お願いできればと思います

2024-05-07 09:30 UTC, mshim03 commented on api/app/tests/medium/routers/test_tags.py
> +
テストについて
- 複数のデータを作成+取得してますが、これはテストに二つのタグが必要というより、パラメータが変更して確かめてます。これはpytest.parametrize を使ってパラメタライズ化しましょう
- assert_200 は複数の責務 (戻ってきたデータをjson化すること、response code が200以外が帰ったら失敗すること)を確かめており、関数名からそれを察知することはできません。またこのテストの主題は HTTP レスポンスが200であることを確かめたいわけではないはずなので、レスポンスコードのに対するassertは不要かと


Given, When, Then を念頭に書くと以下のようになるかと思います
```suggestion
@pytest.mark.parametrize(
    "tag_name",
    [
        "a1:a2:",
        "b1:b2:b3"
    ],
)
def test_it_should_return_tag_data_when_it_requested_existing_tagid(tag_name):
    # Given
    # 予めtagが作成されており
    create_user(USER1)
    tag = create_tag(USER1, tag_name)

    # When
    # ユーザがtag_id を指定してリクエストした場合
    response = client.get("/tags/" + str(tag.tag_id), headers=headers(USER1)))
    fetched_tag = response.json()
    
    # Then
    # 取得したデータには、タグ作成時と同じ情報が含まれている
    assert fetched_tag["tag_id"] == str(tag.tag_id)
    assert fetched_tag["tag_name"] == str(tag1.tag_name)
    assert fetched_tag["parent_id"] == str(tag.parent_id)
    assert fetched_tag["parent_name"] == str(tag.parent_name)
```

2024-05-08 01:12 UTC, dejima-shikou commented on api/app/tests/medium/routers/test_tags.py
> +
指摘の通り修正しました。

2024-05-08 02:00 UTC, mshim03 approved these changes
LGTM

2024-05-08 02:00 UTC, merged