Topic/update models
nttcom/threatconnectome pull request #162
Opened 2024-05-10 02:20 UTC by soum-kazuaki

## PR の目的

- SSVCに基づくAlert通知に向けてDBモデルを拡張

## 経緯・意図・意思決定

- SSVCの各パラメータ用にEnumを定義
  - Enum の値はカルキュレータに合わせている
    - https://certcc.github.io/SSVC/ssvc-calc/
    - Safety Impact もカルキュレータに合わせて Version 1.0 としているが、2.0 が存在するので対応が必要かもしれない
      - https://certcc.github.io/SSVC/reference/decision_points/safety_impact/
  - Automatable のみ、yes/no の二択なので bool 型にしているが、Enum で揃えた方が扱いやすいかもしれない
- Topic
  - 旧来の threat_impact は残存（後方互換のため。SSVC 計算には使わない想定）
  - アクション作成用のデータモデルは未定のため、ひとまず `hint_for_action` の Text カラムを用意している
- Alert
  - ライフサイクルが未確定だが、ひとまず Ticket が消えても Alert は残る形にしてある
  - ただし、Ticket が消えると通知先が何だったか分からなくなる（いずれライフサイクルに合わせた調整が要る）

alembic revision は Enum が苦手らしい。
create table 時なら問題ないのだが、add column では Enum を自動生成してくれないので手動で作ってやる必要があった。
downgrade 時に自動削除してくれないのも相変わらず。

2024-05-10 02:46 UTC, dejima-shikou commented
モデリング打ち合わせで、下記を入れる話があったと思います。

Ticket
　created_at
　update_at

Alert 
　alerted_at

2024-05-10 02:50 UTC, mshim03 requested changes
server_default を利用せず、 `__init__` でデフォルト値を指定するようにお願いします

2024-05-10 03:14 UTC, soum-kazuaki commented on api/app/models.py
> +    )
DBにcommit/flush するまで確定しないという指摘はその通りですが、その状態の ORM オブジェクトを取りまわす方が間違っていると思います。

2024-05-13 02:40 UTC, mshim03 approved these changes
LGTM

2024-05-13 02:40 UTC, merged