Topic/create ticket
nttcom/threatconnectome pull request #164
Opened 2024-05-13 08:03 UTC by dejima-shikou

## PR の目的
- ticket作成処理を追加。
  - threat作成処理の延長で実行される。
  - ssvc_deployer_priorityの計算は未実装であり、現状は固定値を返す。
  - testsフォルダにおいて、integrationsとrequestsの両方から参照される処理はcommonフォルダに置く。

2024-05-13 11:16 UTC, mshim03 requested changes
ssvcの計算方法、threat_impactの計算方法など変更お願いします

2024-05-13 11:16 UTC, mshim03 commented on api/app/tests/integrations/test_dependency.py
> +)
このテストで確かめたいことは、「service_mission_impact, dependency_mission_impactの値が与えられた時、計算されるmission impactが期待通りになっているか」ですよね？

mission_impactの計算ロジックを確かめるためには、 models.Service、models.Dependencyが存在すればいいので、
データを永続化する必要はなさそうです。

```python
@pytest.mark.parametrize(
    "service_mission_impact, dependency_mission_impact, expected_mission_impact",
    [
        # Prioritize dependency_mission_impact.
        (
            models.MissionImpactEnum.CRIPPLED,
            models.MissionImpactEnum.DEGRADED,
            models.MissionImpactEnum.DEGRADED,
        ),
        # If dependency_mission_impact is None, service_mission_impact is enabled.
        (
            models.MissionImpactEnum.CRIPPLED,
            None,
            models.MissionImpactEnum.CRIPPLED,
        ),
        # The models.MissionImpactEnum.NONE is considered specified.
        (
            models.MissionImpactEnum.DEGRADED,
            models.MissionImpactEnum.NONE,
            models.MissionImpactEnum.NONE,
        ),
        (
            models.MissionImpactEnum.NONE,
            models.MissionImpactEnum.DEGRADED,
            models.MissionImpactEnum.DEGRADED,
        ),
    ],
)
def test_calculate_mission_impact(
    service_mission_impact: models.MissionImpactEnum,
    dependency_mission_impact: models.MissionImpactEnum,
    expected_mission_impact: models.MissionImpactEnum,
):
    service = models.Service(略, service_mission_impact=service_mission_impact)
    dependency = models.Dependency(略, dependency_mission_impac=dependency_mission_impact)
    service.dependencies.append(dependency)
    
    assert dependency.calculate_mission_impact == expected_mission_impact
```

2024-05-14 06:27 UTC, dejima-shikou commented on api/app/routers/threat.py
> +    ticket.create_ticket(db, threat)
ticket.pyを削除します。
app/ssvc.pyファイルを作ります。
utils.pyはファイル名から役割を推測しにくいため、できるだけ中身が分かるファイル名にしたいと思います。

2024-05-14 06:28 UTC, dejima-shikou commented on api/app/persistence.py
> +    ).one_or_none()
1. 指摘の通り修正しました。
2. ssvc.py　にロジックを持たせました。

2024-05-14 06:29 UTC, dejima-shikou commented on api/app/ticket.py
> +    )
指摘の通り、DBに依存しないよう修正しました。

2024-05-14 06:30 UTC, dejima-shikou commented on api/app/tests/common/threat_utils.py
> +        )
今回は修正していません。

2024-05-14 06:30 UTC, dejima-shikou commented on api/app/tests/integrations/test_ticket.py
> +    assert ticket is None
名前変更しました。

2024-05-14 06:30 UTC, dejima-shikou commented on api/app/tests/integrations/test_ticket.py
> +def test_create_ticket(testdb: Session):
名前変更しました。

2024-05-14 06:30 UTC, dejima-shikou commented on api/app/tests/integrations/test_dependency.py
> +)
指摘の通り修正し、smallに置きました。

2024-05-14 09:18 UTC, merged