create TicketStatus
nttcom/threatconnectome pull request #175
Opened 2024-05-21 09:17 UTC by dejima-shikou

## PR の目的

- 以下のケースにおいてPTeamTopicTagStatusが生成、CurrentPTeamTopicTagStatusが更新される際、合わせてTicketStatus、CurrentTicketStatusも変更する。
  - pteams/{pteam_id}/topicstatus/{topic_id}/{tag_id}
  - オートクローズ
  - 下記関数が呼ばれるケースにおけるCurrentPTeamTopicTagStatus更新に合わせたCurrentTicketStatusの更新は、未対応。
  - command.py　fix_current_status_by_pteam()
  - command.py　fix_current_status_by_deleted_topic()
  - command.py　fix_current_status_by_topic()
  
- models.py
  - Threat→Ticket、Ticket→Alert、Ticket→TicketStatusの関係を取得した際に型が配列になっていたため、1対1対応となるよう指定。
  - CurrentTicketStatus生成時にcurrent_status_idの初期化が漏れていたため処理追加。
  - CurrentTicketStatus.status_idの参照先誤りを訂正
  
- api/app/alembic/versions/f196d35697d4_add_ticket_status.py
  - models.pyの修正に伴う変更（2テーブルの参照設定のため、テーブル生成順を入れ替えた）

2024-05-21 10:34 UTC, mshim03 requested changes
tikcetstatusの変更部分は大きな問題はないと思います
テスト周りは修正した方がいいかと思います

2024-05-21 10:34 UTC, mshim03 commented on api/app/ticket_manager.py
> +    topicStatusRequest: schemas.TopicStatusRequest,
schemasはFastAPI のレイヤーの構造を定義するものなので、内部のレイヤーに使わない方が本当はいいと思います (改修優先度は低め)

2024-05-21 10:34 UTC, mshim03 commented on api/app/tests/integrations/test_ticket_status.py
> +def test_PTeamTopicTagStatus_equals_TicketStatus_when_create_topicstatus2(
`CurrentPTeamTopicTagStatus` と `CurrentTicketStatus` が同じになることを確認するのではなく、単純に期待される CurrentTicketStatusを記述した方がいいと思います
今の実装だとテストコードからどんなステータスが帰ってくるのが期待される挙動かわからないですし、 CurentPTeamTopicTagStatus｀を削除した時にテストコードが全部書き直しになってしまうかと

2024-05-21 10:34 UTC, mshim03 commented on api/app/tests/integrations/test_ticket_status.py
> +def test_PTeamTopicTagStatus_equals_TicketStatus_when_auto_close(
こちらも同様に、純粋にTicketStatusがどうなるかテストした方がいいと思います

2024-05-21 10:34 UTC, mshim03 commented on api/app/tests/integrations/test_ticket_status.py
> +    assert ticket is not None
これはfixture(共通処理をまとめたもの) なので、assert はしないでください

2024-05-22 04:37 UTC, dejima-shikou commented on api/app/tests/integrations/test_ticket_status.py
> +def test_PTeamTopicTagStatus_equals_TicketStatus_when_create_topicstatus2(
指摘の通り修正しました。
test_PTeamTopicTagStatus_equals_TicketStatus_when_auto_close()
も同様。

2024-05-22 04:37 UTC, dejima-shikou commented on api/app/ticket_manager.py
> +    topicStatusRequest: schemas.TopicStatusRequest,
以下の理由より、対応していません。
・優先度が低い
・別の方式にするとコード量が増えて読みにくくなりそう

2024-05-22 04:38 UTC, dejima-shikou commented on api/app/tests/integrations/test_ticket_status.py
> +    assert ticket is not None
fixtureからassert を削除し、別の方式でNoneチェックしました。

2024-05-22 04:40 UTC, dejima-shikou commented
現状の指摘は対応済です。
その他、auto_closeのテストにおいて修正箇所を通っていないことが分かったため、
Whenのtopics更新で「"disabled": True」の後、「"disabled": False」を実行するよう追加しました。

2024-05-23 04:44 UTC, mshim03 approved these changes
LGTM

2024-05-23 04:44 UTC, merged