Topic/create status api
nttcom/threatconnectome pull request #193
Opened 2024-06-10 07:58 UTC by dejima-shikou

## PR の目的
- 下記2件の、Service単位のステータス変更APIを追加する。
  - POST /pteams/{pteam_id}/services/{service_id}/topicstatus/{topic_id}/{tag_id}
  - GET /pteams/{pteam_id}/services/{service_id}/topicstatus/{topic_id}/{tag_id}

## 経緯・意図・意思決定
- 現在の仕様に合わせてGETは複数のTicketStatus の1つを返すが、CurrentTicketStatus.updated_atが一番古いものを返す。
理由は、ユーザがステータス操作をした後、同じTopicに別Ticketが追加された場合、ユーザが操作済のステータスを表示したいため。

2024-06-10 10:02 UTC, mshim03 requested changes
全体的な記述の修正をお願いします

2024-06-10 10:02 UTC, mshim03 commented on api/app/tests/integrations/test_ticket_status.py
> +                assert status.scheduled_at == datetime(2024, 5, 1)
all()でもいけそう
```suggestion
            assert all(assignee in threat_data["assignees"] for assignee in statsu.assignees)
            assert status.scheduled_at == datetime(2024, 5, 1)
```

2024-06-10 10:02 UTC, mshim03 commented on api/app/tests/integrations/test_ticket_status.py
> +                assert status.scheduled_at == datetime(2024, 5, 2)
ここも同様にallでも可能

2024-06-11 00:02 UTC, dejima-shikou commented on api/app/routers/pteams.py
> +        for threat in persistence.search_threats(db, dependency.dependency_id, topic_id):
Dependencyは"service_id","tag_id","version","target"の4項目で一意です。
CurrentTicketStatus.updated_atが一番古いものを返す関係上、
見つけた１件目を返すget_dependency_from_service_id_and_tag_id()は使えないと思います。

2024-06-11 00:14 UTC, dejima-shikou commented on api/app/routers/pteams.py
> +                    firstest_status = ticket_status
上記２件、指摘の通り修正します。
ただ、TicketStatusはupdated_atを持たないため、下記とします。
firstest_status.updated_at
↓
firstest_status.current_ticket_status.updated_at

2024-06-11 00:23 UTC, dejima-shikou commented on api/app/ticket_manager.py
> +    )
指摘の通り修正します。

2024-06-11 01:03 UTC, dejima-shikou commented on api/app/tests/integrations/test_ticket_status.py
> +        status = ticket_statuses_list[statuses_index]
指摘の通り修正します。

2024-06-11 01:06 UTC, dejima-shikou commented on api/app/tests/integrations/test_ticket_status.py
> +                assert status.scheduled_at == datetime(2024, 5, 2)
同様の箇所をallにします。

2024-06-11 01:13 UTC, dejima-shikou commented
@mshim03 
全指摘に対しての修正をプッシュしました。

2024-06-11 01:51 UTC, mshim03 reviewed
updated_at をcreated_at に変更することも検討お願いします

2024-06-11 01:51 UTC, mshim03 commented on api/app/routers/pteams.py
> +                    firstest_status = ticket_status
TicketStatusはupdated_at がなくて、created_at しかないのを見落としていました

TicketStatus に updated_at がないので、 `ticket_status.update_at` もNoneになりそうです。
`ticket_status.created_at` を使うのが良い気もします

またfirstest という単語は存在しないようです (first自体が1番、という意味を持っているため)
oldest_status などの方が意味が伝わりやすいかもしれません

2024-06-11 06:42 UTC, dejima-shikou commented on api/app/routers/pteams.py
> +                    firstest_status = ticket_status
@mshim03 
firstest _status　→　oldest_status
とします。

現状、Ticket生成時にはCurrentTicketStatusだけ生成してTicketStatusを生成しません。
そのため、TicketStatus.created_atを比較に使うのはNGだと思います。
よって、元のoldest_updated_atを持つ方式に戻します。
※CurrentTicketStatus.updated_atは下記で設定しています。
    current_status.updated_at = (
        None if new_status.topic_status == models.TopicStatusType.completed else topic.updated_at

2024-06-11 06:52 UTC, dejima-shikou commented on api/app/routers/pteams.py
> +                    firstest_status = ticket_status
上記修正をプッシュしました。

2024-06-11 07:03 UTC, mshim03 approved these changes
LGTM

2024-06-11 07:03 UTC, merged