refactor filter param
nttcom/threatconnectome pull request #245
Opened 2024-07-09 08:18 UTC by dejima-shikou

## PR の目的

- StatusページのiFilter (threat imapctによるフィルタリング) のリファクタリング
  - Statusページのthreat imapctによるフィルタリングによるURLパラメータを、従来のiFilterから、以下の形式に変更する。
"immediate"を表示する：immediate=on
"offcycle"を表示する：offcycle=on
"acceptable"を表示する：acceptable=on
"none"を表示する：none=on
※それぞれ、表示しない場合はimmediateなどのパラメータをURLから削除する。
　4つ全て指定していない場合、すべて表示する。

## 経緯・意図・意思決定
従来はURLのパラメータに「iFilter=1100」のように4種類のthreat imapct毎にビットを立てていたため、意味が分かりにくかった。

2024-07-09 12:49 UTC, mshim03 requested changes
impact name と数値の関係性がコードの至る所に散らばっており、変更容易性が低くなってるように見えました
修正案を出してみましたので、ご意見いただければ思います

2024-07-09 12:49 UTC, mshim03 commented on web/src/pages/Status.jsx
> +        : getThreatImpactOn(parseInt(tag.threat_impact ?? 4))) && // show only selected
```suggestion
        : impactFilters.includes(threatImpactName[parseInt(tag.threat_impact ?? 4)]) ) && // show only selected
```

2024-07-09 12:49 UTC, mshim03 commented on web/src/pages/Status.jsx
> +
```suggestion
    impactFilter = impactName
    if (checked) {
      impactFilter.push(impactName)
    }  else {
      impactFilter = impactFilter.filter(filter => filter !== impactName)
    }
    paramse.set("impactFilter",  impactFilter)
```

2024-07-09 12:49 UTC, mshim03 commented on web/src/pages/Status.jsx
> +          const checked = getThreatImpactOn(idx + 1);
本当は `{[0, 1, 2, 3].map((idx) => {` ではなく、　threat_impact の文字列表現 (imemdiate, offcycle...)でmapした方が読み手がわかりやすい気がします
`{Object.values(threatImpactName).map(impactName => {`


数値でmapを続ける場合は以下
```suggestion
          const impactName = threatImpactName[idx + 1]
          const checked = impactFilters.includes(impactName])
```

2024-07-10 04:54 UTC, dejima-shikou commented on web/src/pages/Status.jsx
> +          const checked = getThreatImpactOn(idx + 1);
指摘通り、URLのparamをimpactFilterの配列に変更しました。

> 本当は {[0, 1, 2, 3].map((idx) => { ではなく、　threat_impact の文字列表現 (imemdiate, offcycle...)でmapした方が読み手がわかりやすい気がします
こちらは、少し影響範囲が広がり、今スプリント中に終わらない見込みのため、対応していません。

2024-07-10 07:06 UTC, mshim03 approved these changes
LGTM

2024-07-10 07:06 UTC, merged