Topic/api topic search
nttcom/threatconnectome pull request #37
Opened 2023-12-14 01:17 UTC by soum-kazuaki

## PR の目的

- トピック検索用apiを実装

## 経緯・意図・意思決定

- 既存のsearch_topicsは内部で利用しているため、get_topics_internal に改名。
  - 内部利用にはオーバースペックなので、いずれ最適化したいところ（本PRでは未実施）。
- トピックが持つ属性全て（アクションは除く）での検索をサポート
  - 無効な内容（例えば存在しないタグ名）を指定してもエラーは返さない
  - ただしゾーンだけは例外で、アクセス権のないゾーンを検索条件に含めた場合は 403 を返す。
  - 検索結果の母集合は、実行したユーザが属する全てのチームを加味してアクセス可能なトピック。ゾーン的にアクセスできないトピックは返されない。
  - artifact tag_name は完全一致。parent tag を指定しても child tag はヒットしない。
  - title, abstract の文字検索は case-insensitive。また、単語検索ではないためスペースなども as is で検索する。
  - empty を示す reserved keyword として `   ` (3 spaces) を定義している。
    - タイトルが empty、タグが未登録、ゾーンが未登録（public）、などの検索に利用可能。
  - `|` (vertical var) で複数指定が可能。弊害として、`|` 自体を検索条件に含めることができない。

2023-12-14 03:32 UTC, soum-kazuaki commented
UI との繋ぎ込みを始めて早々に topic_id での検索が抜けていたのに気付いたので追加しました。orz

2023-12-14 05:48 UTC, mshim03 requested changes
空文字列の仕様は変更をお願いします

2023-12-14 05:48 UTC, mshim03 commented on api/app/routers/topics.py
> +    creator_ids: str = Query(""),
default=None にするのではダメでしょうか？ (あと max_lengthも追加)

手元で試した感じでは、引数なしはNone、引数ありで空文字列は空文字列と使い分けられそうです
以下は引数ありで空文字列の場合
```
"GET /topics/search?offset=0&limit=10&sort_key=threat_impact&tag_names= HTTP/1.1" 200 OK
```

```suggestion
    threat_impacts: Optional[str] = Query(default=None, max_length=50),
    topic_ids: Optional[str] = Query(default=None, max_length=50),
    title_words: Optional[str] = Query(default=None, max_length=50),
    abstract_words: Optional[str] = Query(default=None), max_length=50,
    tag_names: Optional[str] = Query(default=None, max_length=50),
    misp_tag_names: Optional[str] = Query(default=None, max_length=50),
    zone_names: Optional[str] = Query(default=None, max_length=50),
    creator_ids: Optional[str] = Query(default=None, max_length=50),
```

2023-12-14 05:48 UTC, mshim03 commented on api/app/routers/topics.py
> +      {"abstract_words": "    "} -> abstract includes "    "
「3空文字列で空白扱い」は利用者にまず伝わらない & 制御フローが複雑になると思うので、この仕様は受け入れるのは難しいです。
Noneと空文字列の違いで吸収できると思うので、ここは変更をお願いします

2023-12-14 05:48 UTC, mshim03 commented on api/app/tests/medium/constants.py
> +MISPTAG3 = "tlp:black"
https://blogs.jpcert.or.jp/ja/2022/09/tlp-v2.html
`tlp:black` は現状使われていないので、 `tlp:red` を利用するのが良いかなと思います

2023-12-14 07:04 UTC, soum-kazuaki commented
empty を意味する reserved keyword を空文字列（""）に変更しました。
なお、testclient と axios とで挙動が違う（前者は None でもクエリパラメータに加える、後者は null だったらクエリパラメータに加えない）ので注意が必要です。

2023-12-14 08:17 UTC, soum-kazuaki commented
query params の Optional が抜けていたので追加しました（エラーにならないのね...）。
また、テスト用の misptag tlp:black を tlp:red に変更しました。
クエリの文字数制限ですが、pydantic や fastapi が文句言わないなら無制限でよい気がします。
（レスポンスサイズに影響する limit は最大 100 に制限してるので、それで十分じゃないかと）

2023-12-15 03:20 UTC, soum-kazuaki commented
query param を array で受け取るように改修しました。
また、threat_impacts を str で受けていたので int に修正しました。

2023-12-18 03:53 UTC, mshim03 approved these changes
LGTM!

2023-12-18 03:53 UTC, merged