topic/add test of set_ticket_status_api
nttcom/threatconnectome pull request #378
Opened 2024-10-01 08:30 UTC by TsurutaYoshiki

## PR の目的
- set_ticket_statusにおけるtopic_status、schduled_atに関するテストについて追加しました。
- pteams.py::set_ticket_status 内の以下のコードに関する部分が正しく正誤判定ができているかを検証しています。

```
if data.topic_status == models.TopicStatusType.scheduled or (
        data.topic_status is None
        and ticket.current_ticket_status.topic_status == models.TopicStatusType.scheduled
    ):
```

## 経緯・意図・意思決定
- 追加したテストは2つです。また新しく作成したテストと既存のテストと被ってたため、既存のテストを削除しました。削除したテストは4つです。
- 追加したテスト
  - test_correct_response_is_received_by_changing_the_topicstatus_and_scheduled_at
    - topic_statusとscheduled_atを変えて正しく正誤判定が行われているかを検証しています。
    - 400が出るものに関してはエラー文が正しく返ってくるかを確認
    - 200が来るものに関してはticekt_idやtopic_statusなどが正しく返ってくるかを確認
  - test_correct_response_is_received_by_checking_the_previous_value_and_the_current_value
    - 前回値を考慮した正誤判定が正しく行えているかを検証しています。
    - pteams.py::set_ticket_status 内の以下のコードが正しく正誤判定できているかを検証しています。
```
if data.topic_status == models.TopicStatusType.scheduled or (
        data.topic_status is None
        and ticket.current_ticket_status.topic_status == models.TopicStatusType.scheduled
    ):
```
```
else:
      if data.scheduled_at is None:
          if ticket.current_ticket_status.topic_status == models.TopicStatusType.scheduled:
```
- 削除したテスト
  - test_it_should_return_400_when_topic_status_is_scheduled_and_there_is_no_schduled_at
  - test_it_should_return_400_when_topic_status_is_acknowledged_and_there_is_schduled_at
  - test_it_should_return_400_when_topic_status_is_scheduled_and_schduled_at_is_in_the_past
  - test_it_should_put_None_in_completed_at_when_schduled_at_is_datetime_fromtimestamp_zero

2024-10-02 04:35 UTC, mshim03 requested changes
テストを抽象的な名前のもの関数に集約してしまったので、テストの理解がかなり難しくなっている印象です。 (parameterize の各要素と引数の各値を読み込み、なおかつシステムに関する前提条件がないとどのようなテストか理解が難しい)
`test_it_should_return_400_when_topic_status_is_acknowledged_and_there_is_schduled_at` などのテストは残し、正常系のテストなどは別途追加した方がいいと思います。

2024-10-02 04:35 UTC, mshim03 commented on api/app/tests/requests/test_pteams.py
> +        def test_correct_response_is_received_by_checking_the_previous_value_and_the_current_value(
「前回値を考慮した正しい値」が具体的に何を意味しているのか、テストパラメータを見ても即座に理解できず、変更容易性がかなり下がっている感じがします

2024-10-03 04:50 UTC, TsurutaYoshiki commented
@mshim03 
- 正常系と異常系のテストを分離しました。また異常系でも失敗する理由が違いものは分離しました。
- `test_correct_response_is_received_by_changing_the_topicstatus_and_scheduled_at`を正常系1つ、異常系3つ、合計4つのテストに分けました。
   - `test_it_should_return_400_when_topic_status_is_alerted`
   - `test_it_should_return_400_when_topic_status_is_not_scheduled_and_schduled_at_is_time`
   - `test_it_should_return_400_when_schduled_at_is_not_future_time`
      - 関数名だけではわかりづらいと思い、コメント文を入れました。
   - `test_it_should_return_200_when_topic_status_and_schduled_at_have_the_correct_values`
- `test_correct_response_is_received_by_checking_the_previous_value_and_the_current_value`を正常系1つ、異常系2つ、合計3つのテストに分けました。全体的に関数名だけでは、分かりづらいと思ったためコメント文入れて説明をしています。
  - `test_it_should_return_400_when_previous_status_is_schduled_and_schduled_at_is_reset`
  - `test_it_should_return_400_when_topic_status_and_scheduled_at_is_not_appropriate`
  - `test_it_should_return_200_when_previous_and_current_status_have_the_correct_values`
- テストで共通して行う部分はcommon_setup_for_set_ticket_status 関数にまとめました。

2024-10-03 05:18 UTC, mshim03 approved these changes
LGTM

2024-10-03 05:18 UTC, merged