topic/create script for collecting threats data
nttcom/threatconnectome pull request #517
Opened 2024-12-09 08:51 UTC by TsurutaYoshiki

## PR の目的
- 特定のサービスに紐づく脆弱性とパッケージ情報を jsonで返すスクリプトの作成しました

## 経緯・意図・意思決定
- 出力形式: json
- 出力内容
```
{
    "pteam_id": "",
    "pteam_name": "",
    "service_id": "",
    "service_name": "",
    "service_description": "",
    "threats": [
        {
            "threat_id": "",
            "topic_id": "",
            "cve_id": [
                "CVE-xxxxx",
                "CVE-xxxxx"
            ],
            "tag_id": "",
            "tag_version": "",
            "tag_name": "axios:npm:npm"
        },
        {
            "threat_id": "",
            "topic_id": "",
            "cve_id": [
                "CVE-xxxxx",
                "CVE-xxxxx"
            ],
            "tag_id": "",
            "tag_version": "",
            "tag_name": "axios:npm:"
        }
    ]
}
```
- スクリプト実行時にAPI_BASE_URL、token、pteam_id、service_idを指定してもらうようにしました
- cve_id内に"CVE-xxxxx"がなかった場合、threatごと取り除いています
- ファイルの出力名をcollect_threats_data + service_idにしています

2024-12-09 23:55 UTC, dejima-shikou commented on scripts/collect_threats_data.py
> +            )
service_id が見つかったら、他のserviceに用がないのでbreakした方が良い

2024-12-10 00:06 UTC, dejima-shikou commented on scripts/collect_threats_data.py
> +
引数のthreatsの値が変わる、という挙動は推奨しない。
新しいlistを作って返す方が分かりやすい。
〇理由
・１つの変数が場所によって状態が変わる、というコードは読みにくい。状態が変わっている箇所を全部追いかけないと理解できないため。定義時から値が変わらなければ、定義箇所を見れば変数の中身が分かって読みやすい。
・getXXX関数は戻り値を返す、その他状態を更新しない、というケースが多く、この慣習に従い、適切な関数名を付けていると、呼び出し元を見るだけでコードの意味が分かる。

2024-12-10 00:08 UTC, dejima-shikou commented on scripts/collect_threats_data.py
> +
threats、_threats は変数名を見ても違いが分からない。
多少長くなっても良いので、違いが分かるような名前が良い。
threats_with_tag_data, threats_with_topic_data とか

2024-12-10 00:14 UTC, dejima-shikou commented
エラー時の挙動を設計してください
・get_pteam
　→見つからなければエラーメッセージを表示して異常終了
・get_threats
　→見つからなければエラーメッセージを表示して異常終了
　　or
　　0件なので特にエラー処理せず、結果戻り値[]
・get_dependency
　→エラーメッセージは出すが、他のthreatの処理は続行
・・・

2024-12-10 00:20 UTC, dejima-shikou commented on scripts/collect_threats_data.py
> +def output_json_file(threats: dict, pteam_id: str, service_id: str):
引数pteam_idは使ってないので消すべき

2024-12-10 01:21 UTC, mshim03 requested changes
関数設計が統一されてないので意図が伝わりにくいです。output_dataを受け取って加工しする関数があったり、データを返してmain側でoutput_data を加工したりとわかりづらいです。
threats という辞書の中身がどんどん変化するので関数の中まで見ないと混乱します。データの流れを明確にしてください

2024-12-10 01:21 UTC, mshim03 commented on scripts/collect_threats_data.py
> +    return _threats
misp_tag の取得と cve_id という値をデータに付与する責務を持っています。関数名がじつ挙動を表してません。責務を分けた方がいいと思います

2024-12-10 07:00 UTC, TsurutaYoshiki commented
スクリプトを修正しました
以下の部分を変更しました
### 全体的な修正
- output_dataをmain関数内で追加、変更を行うようにしました
- threats という辞書型のデータを加工していくのではなく、関数ごとに新しい変数をリターンするようにしました

### 部分的な修正
- def get_pteam_and_service_data()内にbreakを追加
- for文の引数を処理中にdelを用いて削除するのをやめました
- def output_json_file()の引数にあるpteam_idの削除
- pteam_id、service_idが間違っていた時のエラー出力

### 上記のPRでの記載忘れ
- スクリプトを実行する際に必要なコマンドの説明をREADMEに追加しました

2024-12-10 07:12 UTC, dejima-shikou commented on scripts/collect_threats_data.py
> +            sys.exit("Is the service_id correct?\n" + str(error))
service_id は正しいが、そのserviceにthreatが1件も無い場合もあるので、
ここではservice_idに紐づくthreatが取得できなかった、とのメッセージが良いと思います。

2024-12-10 08:21 UTC, TsurutaYoshiki commented
エラーメッセージを変更しました
Is the service_id correct?
↓
There is no threat tied to service_id

2024-12-10 09:59 UTC, mshim03 approved these changes
LGTM

2024-12-10 09:59 UTC, merged