Restrict get_threat to fetch threats belonging to the user's pteam
nttcom/threatconnectome pull request #520
Opened 2024-12-10 01:46 UTC by shihakata

## PR の目的

- 機能追加の場合
  - #xxx yyy を可能にする(xxx は issue 番号)
- バグ改修の場合
  - #xxx yyy のため、zzz を修正(xxx は issue 番号)

## 経緯・意図・意思決定

このプルリクエストに至った経緯や背景情報や事情、
また実装の際に考慮したこと、意思決定があれば記述する。

このプルリクエストの対象外とした内容があるならば、その理由も含めて記述する。

## 参考文献

2024-12-10 23:55 UTC, dejima-shikou commented on api/app/command.py
> +        select_stmt = select_stmt.where(models.Account.user_id == current_user.user_id)
current_userがNoneのケースは無いのでif文は不要と思います。

2024-12-10 23:56 UTC, dejima-shikou commented on api/app/command.py
>                  models.Dependency.dependency_id == models.Threat.dependency_id,
この条件はjoin句にあるので、ここでは不要

2024-12-10 23:58 UTC, dejima-shikou commented on api/app/command.py
> +    )
分岐が無い場合は、毎回変数select_stmt に入れるのではなく、.join().join()と繋げれば良いです。

2024-12-11 00:09 UTC, dejima-shikou commented on api/app/command.py
> +    )
join()の第二引数に結合条件を書いてますが、これは単なる外部キーによる結合条件だけであれば、省略できるようです。commandの他のjoin呼び出しを参考にしてください。

2024-12-11 02:31 UTC, shihakata commented on api/app/command.py
> +        select_stmt = select_stmt.where(models.Account.user_id == current_user.user_id)
search_threatsはget threats以外の部分でも使用されていて、それに影響を及ぼさないようにNoneをデフォルト値として設定しているのですが、全部current_userを用いるように修正した方がいいでしょうか？

2024-12-11 02:35 UTC, dejima-shikou commented on api/app/command.py
> +        select_stmt = select_stmt.where(models.Account.user_id == current_user.user_id)
他の呼び出し箇所を把握しておらずすみません。
現状のままで良いです。

2024-12-11 05:52 UTC, soum-kazuaki commented on api/app/routers/threat.py
> +        raise HTTPException(status_code=status.HTTP_403_FORBIDDEN, detail="Not a pteam member")
check membership は検索処理より前に実施した方がよいです。
権限が無い人には当該 threat の有無の情報も与えない、という方が安全なので。

2024-12-11 05:54 UTC, soum-kazuaki commented on api/app/routers/threat.py
> +        raise HTTPException(status_code=status.HTTP_403_FORBIDDEN, detail="Not a pteam member")
ごめんなさい、撤回します。
threat 個別指定なので、検索処理を先にやらないと判別不能ですね。失礼しました。

2024-12-11 08:59 UTC, mshim03 requested changes
引数名の変更をお願いします

2024-12-11 08:59 UTC, mshim03 commented on api/app/command.py
> +    current_user: models.Account | None = None,
`current_user` はAPI側の用語が漏出しているので、 `user_id` に変更してください

2024-12-12 08:33 UTC, mshim03 approved these changes
LGTM

2024-12-12 08:33 UTC, merged