Topic/upload SBOM file api
nttcom/threatconnectome pull request #64
Opened 2024-01-30 05:04 UTC by kojima520

## PR の目的
SBOMアップロードAPIの実装

## 経緯・意図・意思決定
### APIの実装（小島担当）
- cdx_tags.py を APIサーバ内の、sbom.pyに移植しました。hostname, skip_ruleはomitしています。
- SBOMアップロードAPIの実装しました。本PRでは、Cyclonedx(trivy, syft)のみ対応。

### APIテスト（鶴田担当）

## 参考文献

2024-01-30 08:52 UTC, mshim03 requested changes
pteams.py 周りの修正をお願いします。 (sbom.py は現時点では修正しなくても良いですが、将来的には変更したいかなと)

2024-01-30 08:52 UTC, mshim03 commented on api/app/sbom.py
> +        return cls.from_string(bomformat)
SbomFormat をパースしてくれるわけではなく、SBOMの判定を行ってくれるクラスなので
`SBOMFormatDetector` のように、判断の能力しか持たないことがわかる名前の方がいいかと思います。
( 現在 gen_cdx_components などで実装している、 CDXComponents クラスのインスタンスを作る機能を SbomFormat クラスに持たせるのなら名前はこのままでいいかと思います。ただ判定機能しか持たせないなら Detector 的な文字列を入れて欲しい)

2024-01-30 08:52 UTC, mshim03 commented on api/app/sbom.py
> +        )
データの保持と出力機能しか持ってないので、dataclass でやった方がいいかもです
https://docs.python.org/ja/3/library/dataclasses.html

この辺で使ってます
https://github.com/nttcom/threatconnectome/blob/d3c0f9869b59528dac969b47612a3bc632d86252/api/app/version.py#L130

2024-01-30 08:52 UTC, mshim03 commented on api/app/routers/pteams.py
> +        SbomFormat.from_jsondata(jdata)  # check sbom format
将来の拡張を考えるなら、一応戻り値の判定もしておいた方がいいと思います (このコードを見た人が迷わないように)

```suggestion
        if SbomFormat.from_jsondata(jdata) == SbomFormat.CDX:
            components = gen_cdx_components(jdata)
```

2024-01-30 08:52 UTC, mshim03 commented on api/app/sbom.py
> +            self.mgr_type = _pick_prop(props, _mgr_type_key)
これは __init__ ではなく、 form_json のようなファクトリーメソッド (jsonを受け取りTrivyCDXComponent を返す ) を用意した方がいいと思います
これだとdictを与えることでしかインスタンスを作れなくなります (bom-ref や type を直接指定してインスタンス作成ができなくなる)

参考
https://github.com/nttcom/threatconnectome/blob/d3c0f9869b59528dac969b47612a3bc632d86252/api/app/version.py#L150

2024-01-30 08:52 UTC, mshim03 commented on api/app/sbom.py
> +    class TrivyCDXComponent:
これもdataclass の方がいい気がします (データの保持がメイン)

2024-01-31 01:37 UTC, kojima520 commented
@mshim03 pteams.py 周りの修正を行いました。
sbom.pyの改善は、別PRとさせてください。

2024-01-31 02:55 UTC, mshim03 approved these changes
LGTM

2024-01-31 02:55 UTC, merged