Topic/models pteam tag reference table
nttcom/threatconnectome pull request #83
Opened 2024-02-09 05:56 UTC by soum-kazuaki

## PR の目的

- PTeamTag.references のモデル化（曖昧な json 型の廃止）

## 経緯・意図・意思決定

- PTeamTagReference テーブルを新設
  - PTeamTag テーブル自体は（移行が完了していないため）残存
- 本 PR で PTeamTagReference テーブルに対応しているのは pteam.py::apply_group_tags() のみ
  - 移行未完の関数が PTeamTag テーブルを参照するため、PTeamTagReference の情報を PTeamTag に書き戻す関数を用意
    - 移行が完了すればお役御免なので、それまでの辛抱
- 仕様的に曖昧な点があり、別途、検討が必要
  - group less なタグ登録の是非
    - pteam_create() 実行時（api 直接実行）
    - add_pteamtag() 実行時（UI でモニタリングターゲット操作）
  - references less なタグ登録の是非
    - group less と同様
    - 更には target less, version less の是非も要検討
  - text の扱い
    - upload_tags_file の入力データとして必須（欠けていた場合は empty string 強制）な一方、グループとは無関係な情報
- 本 PR では、group, references, target, version が必須で欠けていた場合には empty (string or array) で補完している
  - 本件の都合もあり、グループ名として empty string は禁止（BadRequest）とした。
  - UI 上にグループとして "" が現れるケースがある（仕様が定まり移行が完了すれば解消する見込み）
  - 同様に、References の target, version として "" が現れるケースがある（かもしれない）
- 既存のテストケースを１箇所、改修している
  - references を List[dict] のまま比較していたが、順序が保証されなくなったため Set[dict] で比較するように改修

2024-02-09 11:22 UTC, mshim03 requested changes
データ作成のロジックなどの変更をお願いします

2024-02-09 11:22 UTC, mshim03 commented on api/app/routers/pteams.py
> +    )
データ作成のロジックがmodels.PTeamTagReferencesとここで分散するので、 `bulk_save_objects` を利用するのが良いと思います
https://docs.sqlalchemy.org/en/20/orm/session_api.html#sqlalchemy.orm.Session.bulk_save_objects

2024-02-09 11:22 UTC, mshim03 commented on api/app/routers/pteams.py
> +        )
ここも bulk_save_objects が良いと思います

2024-02-13 00:26 UTC, soum-kazuaki commented on api/app/routers/pteams.py
> +    db.refresh(pteam)
ここで commit しないと続く処理で外部キー制約違反（pteam_id 不在）で蹴られるのですが、それは ORM と direct sql を混ぜたのが原因でした。
ORM 操作に統一することで、ここでの commit を廃止しました。

2024-02-13 00:34 UTC, soum-kazuaki commented on api/app/routers/pteams.py
> +    )
貼ってくださったリンクによると bulk_save_objects は sqlalchemy 2.0 では legacy 扱いで、上記のスタイルへのリンクが貼ってあります。

あと、指摘の内容はどちらかと言えば model 生成ではなく、リクエストデータの曖昧さ（target, version 不在時の処理）をどこで吸収するかの話のような気もします。

2024-02-13 00:41 UTC, soum-kazuaki commented on api/app/routers/pteams.py
> +        )
bulk_save_object が legacy なのは同上ですが、ここは upsert （insert or update）なので postgresql 固有の `insert().on_conflict_do_update()` を使用しています。
https://docs.sqlalchemy.org/en/20/orm/queryguide/dml.html#orm-upsert-statements

2024-02-13 01:59 UTC, mshim03 commented on api/app/routers/pteams.py
> +    )
PTeamTagReferenceのidはランダムなuuid値を使っている、というロジックがroutersに漏れているのを気にしています (uuid算出ロジックが変わった時に、models.PTeamTagReferenceと整合性をとり自前生成しているコード全部を変更する必要がある)

https://docs.sqlalchemy.org/en/20/orm/session_api.html#sqlalchemy.orm.Session.add_all
add_all() でもそこまでパフォーマンス上の影響は生じないのではないかと

2024-02-13 08:49 UTC, soum-kazuaki commented
models オブジェクトの挿入処理を ORM(legacy) 側に寄せました。
なお、ORM か否かに関わらず、関数外部での更新後は db.flush() （更には必要に応じて再取得 or db.refresh(x)）しないと不整合が発生する可能性があります。
この辺りは全体的に見直し（必要ならルール化）が必要です。

また、PTeamTag.text はグループ指定操作から切り離す方針となっていますが、本 PR では未対応です（テストコードへの影響が大きいため）。

2024-02-13 09:12 UTC, mshim03 approved these changes
LGTM

2024-02-13 09:12 UTC, merged